{% set name = "stgit" %}
{% set version = "2.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stacked-git/stgit/archive/v{{ version }}.tar.gz
  sha256: 087ec6b4aec92522687ede9fb249c98ac49e183f8bdd58c8015deaf69919d7e3

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - pkg-config
  host:
    - curl
    - git
    - libcurl
    - zlib
  run:
    - git

test:
  commands:
    - stg --help

about:
  home: https://stacked-git.github.io
  license: GPL-2.0-only
  license_file: 
    - COPYING
    - THIRDPARTY.yml
  summary: Manage Git commits as a stack of patches
  dev_url: https://github.com/stacked-git/stgit

extra:
  recipe-maintainers:
    - danielnachun
