context:
  version: "2.5.2"

package:
  name: stgit
  version: ${{ version }}

source:
  url: https://github.com/stacked-git/stgit/archive/v${{ version }}.tar.gz
  sha256: 73c1f31e71eab3ddbfe831f006e5b427e8aabb6c8cc8377425eb073fc551f2c3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - pkg-config
  host:
    - curl
    - git
    - libcurl
    - zlib
  run:
    - git

tests:
  - script:
      - stg --help

about:
  license: GPL-2.0-only
  license_file:
    - COPYING
    - THIRDPARTY.yml
  summary: Manage Git commits as a stack of patches
  homepage: https://stacked-git.github.io
  repository: https://github.com/stacked-git/stgit

extra:
  recipe-maintainers:
    - danielnachun
