context:
  version: "2.5.0"

package:
  name: stgit
  version: ${{ version }}

source:
  url: https://github.com/stacked-git/stgit/archive/v${{ version }}.tar.gz
  sha256: 1cc1c2771387bff56865f1b1e8f6dc07dfca54e0d923e506fc71c2a6ff531913

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - pkg-config
  host:
    - curl
    - git
    - libcurl
    - zlib
  run:
    - git

tests:
  - script:
      - stg --help

about:
  license: GPL-2.0-only
  license_file:
    - COPYING
    - THIRDPARTY.yml
  summary: Manage Git commits as a stack of patches
  homepage: https://stacked-git.github.io
  repository: https://github.com/stacked-git/stgit

extra:
  recipe-maintainers:
    - danielnachun
